(defun decode-header (&rest bytes)
  (check-type bytes cons)
  (assert (member (length bytes) '(4 5)))
  (if (= #x60 (logand #xe0 (elt bytes 1)))
      (format t "~&indirect stamp header, write mode ~d, string @ $~4,'0x, x = ~d, palette ~d, width ~d (~d)" 
              (ash (logand #x80 (elt bytes 1)) -7)
              (+ (* #x100 (elt bytes 2)) (elt bytes 0))
              (if (< (elt bytes 4) 168) 
                  (elt bytes 4)
                  (- (elt bytes 4) #x100))
              (ash (logand (elt bytes 3) #xe0) -5)
              (1+ (logxor #x1f (logand #x1f (elt bytes 3))))
              (* 8 (1+ (logxor #x1f (logand #x1f (elt bytes 3))))))
      (progn (format t "~&direct stamp header, ")
             (if (= 0 (logand #x1f (elt bytes 1)))
                 (format t "extended, write mode ~d, stamp @ $~4,'0x, x = ~d, palette ~d, width ~d (~d)"
                         (ash (logand #x80 (elt bytes 1)) -7)
                         (+ (* #x100 (elt bytes 2)) (elt bytes 0))
                         (if (< (elt bytes 4) 168) 
                             (elt bytes 4)
                             (- (elt bytes 4) #x100))
                         (ash (logand (elt bytes 3) #xe0) -5)
                         (1+ (logxor #x1f (logand #x1f (elt bytes 3))))
                         (* 8 (1+ (logxor #x1f (logand #x1f (elt bytes 3))))))
                 (format t "stamp @ $~4,'0x, x = ~d, palette ~d, width ~d (~d)"
                         (+ (* #x100 (elt bytes 2)) (elt bytes 0))
                         (if (< (elt bytes 3) 168)
                             (elt bytes 3) 
                             (- (elt bytes 3) #x100))
                         (ash (logand (elt bytes 1) #xe0) -5)
                         (1+ (logxor #x1f (logand #x1f (elt bytes 1))))
                         (* 8 (1+ (logxor #x1f (logand #x1f (elt bytes 1))))))))))

(defun decode-hex-header (string)
  (apply #'decode-header
         (loop for i from 0 by (if (find #\space string) 3 2)
               while (< i (length string))
               collecting (parse-integer (subseq string i (+ i 2)) :radix 16))))
